<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magento\Shipping\Block\Adminhtml\Order\Tracking\View */ ?>
<?php $order = $block->getShipment()->getOrder();?>
<?php $isRedJePakketje = (strpos($order->getShippingMethod(), 'redjepakketje') !== false); ?>
<?php $labelHelper = $this->helper('\Cream\RedJePakketje\Helper\LabelHelper'); ?>
<?php $trackingHelper = $this->helper('\Cream\RedJePakketje\Helper\TrackingHelper'); ?>
<div class="admin__control-table-wrapper">
    <table class="data-table admin__control-table" id="shipment_tracking_info">
        <thead>
            <tr class="headings">
                <th class="col-carrier"><?= /* @escapeNotVerified */ __('Carrier') ?></th>
                <th class="col-title"><?= /* @escapeNotVerified */ __('Title') ?></th>
                <th class="col-number"><?= /* @escapeNotVerified */ __('Number') ?></th>
                <?php if ($isRedJePakketje) : ?>
                    <th class="col-email">
                        <?= /* @escapeNotVerified */ __('Track & Trace') ?>
                    </th>
                    <th class="col-download">
                        <?= /* @escapeNotVerified */ __('Label') ?>
                    </th>
                <?php endif ?>
                <th class="col-delete last"><?= /* @escapeNotVerified */ __('Delete') ?></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td class="col-carrier">
                    <select name="carrier"
                            class="select admin__control-select"
                            onchange="selectCarrier(this)">
                        <?php foreach ($block->getCarriers() as $_code => $_name): ?>
                        <option value="<?= /* @escapeNotVerified */ $_code ?>"><?= $block->escapeHtml($_name) ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td class="col-title">
                    <input class="input-text admin__control-text"
                           type="text"
                           id="tracking_title"
                           name="title"
                           value="" />
                </td>
                <td class="col-number">
                    <input class="input-text admin__control-text"
                           type="text"
                           id="tracking_number"
                           name="number"
                           value="" />
                </td>
                <td class="col-delete last" <?php if ($isRedJePakketje) : ?>colspan="3" <?php endif; ?>>
                    <?= $block->getSaveButtonHtml() ?>
                </td>
            </tr>
        </tfoot>
    <?php if ($_tracks = $block->getShipment()->getAllTracks()): ?>
        <tbody>
        <?php $i = 0; foreach ($_tracks as $_track):$i++ ?>
            <tr class="<?= /* @escapeNotVerified */ ($i%2 == 0) ? 'even' : 'odd' ?>">
                <td class="col-carrier"><?= $block->escapeHtml($block->getCarrierTitle($_track->getCarrierCode())) ?></td>
                <td class="col-title"><?= $block->escapeHtml($_track->getTitle()) ?></td>
                <td class="col-number">
                    <?php if ($_track->isCustom()): ?>
                    <?= $block->escapeHtml($_track->getNumber()) ?>
                    <?php else: ?>
                        <?php if ($isRedJePakketje) : ?>
                            <?php $trackingUrl = $trackingHelper->getTrackingUrl($_track) ?>
                            <?php if ($trackingUrl) : ?>
                                <a href="<?= /* @escapeNotVerified */ $trackingUrl ?>" target="_blank"><?= /* @escapeNotVerified */ $block->escapeHtml($_track->getNumber()) ?></a>
                            <?php else: ?>
                                <?= /* @escapeNotVerified */ $block->escapeHtml($_track->getNumber()) ?>
                            <?php endif ?>
                        <?php else: ?>
                            <a href="#" onclick="popWin('<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($_track) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"><?= $block->escapeHtml($_track->getNumber()) ?></a>
                        <?php endif ?>
                    <div id="shipment_tracking_info_response_<?= /* @escapeNotVerified */ $_track->getId() ?>"></div>
                    <?php endif; ?>
                </td>
                <?php if ($isRedJePakketje) : ?>
                    <td class="col-email col-actions">
                        <a href="<?= /* @escapeNotVerified */ $trackingHelper->getSendTrackMailUrl($_track) ?>"
                           title="<?= /* @escapeNotVerified */ __("Send Tracking Information to Customer") ?>"
                           class="action-email action-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" height="24" class="action-email-icon">
                                <path fill="currentColor"
                                      d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"
                                ></path>
                            </svg>
                        </a>
                    </td>

                    <td class="col-download col-actions">
                        <a href="<?= /* @escapeNotVerified */ $labelHelper->getDownloadUrl($_track) ?>"
                           title="<?= /* @escapeNotVerified */ __("Download Shipping Label") ?>"
                           class="action-download action-icon" target="_blank">
                        </a>
                    </td>
                <?php endif ?>
                <td class="col-delete col-actions last">
                    <button class="action-delete action-icon" type="button" title="<?= /* @escapeNotVerified */ __('Delete Track & Trace Number And Shipping Label') ?>"
                            onclick="deleteTrackingNumber('<?= /* @escapeNotVerified */ $block->getRemoveUrl($_track) ?>'); return false;">
                        <span><?= /* @escapeNotVerified */ __('Delete') ?></span>
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
    </table>
</div>

<script>
require(['prototype'], function(){

//<![CDATA[
function selectCarrier(elem) {
    var option = elem.options[elem.selectedIndex];
    $('tracking_title').value = option.value && option.value != 'custom' ? option.text : '';
}

function deleteTrackingNumber(url) {
    if (confirm('<?= /* @escapeNotVerified */ __('Are you sure?') ?>')) {
        submitAndReloadArea($('shipment_tracking_info').parentNode, url)
    }
}

window.selectCarrier = selectCarrier;
window.deleteTrackingNumber = deleteTrackingNumber;
//]]>

});
</script>
